local icons = {
	C_All_H_All_01Job_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 522, 85, 85}},
	C_All_H_All_AllJobs_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 522, 85, 85}},
	C_All_H_All_AllJobs_D2 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {435, 783, 85, 85}},
	C_All_H_All_AllJobs_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {609, 348, 85, 85}},
	C_All_H_All_AllJobs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 609, 85, 85}},
	C_All_H_All_AllJobs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {435, 696, 85, 85}},
	C_All_H_All_AllJobs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 522, 85, 85}},
	C_All_H_All_AllLevel005 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 0, 85, 85}},
	C_All_H_All_AllLevel010 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 522, 85, 85}},
	C_All_H_All_AllLevel025 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 783, 85, 85}},
	C_All_H_All_AllLevel050 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {348, 435, 85, 85}},
	C_All_H_All_AllLevel075 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 87, 85, 85}},
	C_All_H_All_AllLevel100 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 87, 85, 85}},
	C_All_H_All_Infamy_01 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {348, 696, 85, 85}},
	C_All_H_All_Infamy_02 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 261, 85, 85}},
	C_All_H_All_Infamy_03 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {0, 87, 85, 85}},
	C_All_H_All_Infamy_04 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {783, 261, 85, 85}},
	C_All_H_All_Infamy_05 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {696, 783, 85, 85}},
	C_All_H_All_Infamy_06 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 174, 85, 85}},
	C_All_H_All_Infamy_07 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {87, 696, 85, 85}},
	C_All_H_All_Infamy_08 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {783, 87, 85, 85}},
	C_All_H_All_Infamy_09 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 522, 85, 85}},
	C_All_H_All_Infamy_10 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {87, 348, 85, 85}},
	C_All_H_All_Infamy_11 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {870, 348, 85, 85}},
	C_All_H_All_Infamy_12 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 435, 85, 85}},
	C_All_H_All_Infamy_13 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {522, 87, 85, 85}},
	C_All_H_All_Infamy_14 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 87, 85, 85}},
	C_All_H_All_Infamy_15 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {0, 696, 85, 85}},
	C_All_H_All_Infamy_16 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 609, 85, 85}},
	C_All_H_All_Infamy_17 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 783, 85, 85}},
	C_All_H_All_Infamy_18 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 0, 85, 85}},
	C_All_H_All_Infamy_19 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {0, 261, 85, 85}},
	C_All_H_All_Infamy_20 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {696, 348, 85, 85}},
	C_All_H_All_Infamy_21 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {609, 783, 85, 85}},
	C_All_H_All_Infamy_22 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 261, 85, 85}},
	C_All_H_All_Infamy_23 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 522, 85, 85}},
	C_All_H_All_Infamy_24 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {870, 0, 85, 85}},
	C_All_H_All_Infamy_25 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 783, 85, 85}},
	C_Bain_H_All_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 87, 85, 85}},
	C_Bain_H_All_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {696, 870, 85, 85}},
	C_Bain_H_All_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {174, 261, 85, 85}},
	C_Bain_H_Arena_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 348, 85, 85}},
	C_Bain_H_Arena_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 261, 85, 85}},
	C_Bain_H_Arena_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 348, 85, 85}},
	C_Bain_H_Arena_Even = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 0, 85, 85}},
	C_Bain_H_Arena_FuckIt_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 870, 85, 85}},
	C_Bain_H_Arena_MFStev = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 696, 85, 85}},
	C_Bain_H_Arena_SoundofSilence = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {609, 522, 85, 85}},
	C_Bain_H_ArtGallery_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {174, 348, 85, 85}},
	C_Bain_H_ArtGallery_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 696, 85, 85}},
	C_Bain_H_ArtGallery_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 696, 85, 85}},
	C_Bain_H_ArtGallery_TheTurtle = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {348, 609, 85, 85}},
	C_Bain_H_ArtGallery_TheWolfLures = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {174, 261, 85, 85}},
	C_Bain_H_BankAny_SaintFrancis_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {696, 87, 85, 85}},
	C_Bain_H_BankC_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {0, 696, 85, 85}},
	C_Bain_H_BankC_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 522, 85, 85}},
	C_Bain_H_BankC_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {87, 870, 85, 85}},
	C_Bain_H_BankD_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {174, 783, 85, 85}},
	C_Bain_H_BankD_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {870, 87, 85, 85}},
	C_Bain_H_BankD_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 609, 85, 85}},
	C_Bain_H_BankG_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 783, 85, 85}},
	C_Bain_H_BankG_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {696, 696, 85, 85}},
	C_Bain_H_BankG_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 870, 85, 85}},
	C_Bain_H_BankR_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 87, 85, 85}},
	C_Bain_H_BankR_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 870, 85, 85}},
	C_Bain_H_BankR_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {0, 783, 85, 85}},
	C_Bain_H_Car_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 87, 85, 85}},
	C_Bain_H_Car_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {87, 174, 85, 85}},
	C_Bain_H_Car_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {522, 609, 85, 85}},
	C_Bain_H_Car_Gone = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {87, 87, 85, 85}},
	C_Bain_H_Car_Tag = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 261, 85, 85}},
	C_Bain_H_CookOff_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 522, 85, 85}},
	C_Bain_H_CookOff_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {87, 696, 85, 85}},
	C_Bain_H_CookOff_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 696, 85, 85}},
	C_Bain_H_CookOff_KissTheChef_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {261, 174, 85, 85}},
	C_Bain_H_DiamondStore_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 522, 85, 85}},
	C_Bain_H_DiamondStore_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {435, 609, 85, 85}},
	C_Bain_H_DiamondStore_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 0, 85, 85}},
	C_Bain_H_GOBank_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 435, 85, 85}},
	C_Bain_H_GOBank_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 261, 85, 85}},
	C_Bain_H_GOBank_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {0, 0, 85, 85}},
	C_Bain_H_GOBank_AllEggs = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {174, 174, 85, 85}},
	C_Bain_H_GOBank_DeadPresents = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 609, 85, 85}},
	C_Bain_H_GOBank_Eco_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {870, 348, 85, 85}},
	C_Bain_H_GOBank_IsEverythingOK = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {87, 0, 85, 85}},
	C_Bain_H_GOBank_SewerRats_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {0, 261, 85, 85}},
	C_Bain_H_GOBank_UpsideDown = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {348, 696, 85, 85}},
	C_Bain_H_GOBank_WeAreAll_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {435, 522, 85, 85}},
	C_Bain_H_JewelryStore_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {696, 870, 85, 85}},
	C_Bain_H_JewelryStore_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {696, 261, 85, 85}},
	C_Bain_H_JewelryStore_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 261, 85, 85}},
	C_Bain_H_JewelryStore_Diamonds = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {0, 348, 85, 85}},
	C_Bain_H_JewelryStore_PrivateParty_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 348, 85, 85}},
	C_Bain_H_ShadowRaid_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 783, 85, 85}},
	C_Bain_H_ShadowRaid_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {435, 348, 85, 85}},
	C_Bain_H_ShadowRaid_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {87, 261, 85, 85}},
	C_Bain_H_ShadowRaid_IAmNinja = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {0, 696, 85, 85}},
	C_Bain_H_ShadowRaid_IHaveNoIdea = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {348, 0, 85, 85}},
	C_Bain_H_ShadowRaid_IWillFade = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {174, 522, 85, 85}},
	C_Bain_H_ShadowRaid_IWillPass = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 0, 85, 85}},
	C_Bain_H_ShadowRaid_IWillTake = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {783, 609, 85, 85}},
	C_Bain_H_ShadowRaid_IWillWalk = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 783, 85, 85}},
	C_Bain_H_TransportAny_ButWait = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {348, 522, 85, 85}},
	C_Bain_H_TransportAny_IDoWhat_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {348, 174, 85, 85}},
	C_Bain_H_TransportAny_IfYouLikedIt = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 435, 85, 85}},
	C_Bain_H_TransportCrossroads_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 0, 85, 85}},
	C_Bain_H_TransportCrossroads_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 696, 85, 85}},
	C_Bain_H_TransportCrossroads_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {435, 87, 85, 85}},
	C_Bain_H_TransportDowntown_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {522, 435, 85, 85}},
	C_Bain_H_TransportDowntown_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {0, 435, 85, 85}},
	C_Bain_H_TransportDowntown_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 696, 85, 85}},
	C_Bain_H_TransportHarbor_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {261, 870, 85, 85}},
	C_Bain_H_TransportHarbor_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 609, 85, 85}},
	C_Bain_H_TransportHarbor_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {0, 783, 85, 85}},
	C_Bain_H_TransportPark_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 522, 85, 85}},
	C_Bain_H_TransportPark_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 87, 85, 85}},
	C_Bain_H_TransportPark_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {87, 348, 85, 85}},
	C_Bain_H_TransportTrainHeist_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 348, 85, 85}},
	C_Bain_H_TransportTrainHeist_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 783, 85, 85}},
	C_Bain_H_TransportTrainHeist_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 435, 85, 85}},
	C_Bain_H_TransportTrainHeist_LetThem = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {609, 261, 85, 85}},
	C_Bain_H_TransportTrainHeist_WereGonnaNeed = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 87, 85, 85}},
	C_Bain_H_TransportUnderpass_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {174, 609, 85, 85}},
	C_Bain_H_TransportUnderpass_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 435, 85, 85}},
	C_Bain_H_TransportUnderpass_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 261, 85, 85}},
	C_Butcher_H_BombDock_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 870, 85, 85}},
	C_Butcher_H_BombDock_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 0, 85, 85}},
	C_Butcher_H_BombDock_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {870, 0, 85, 85}},
	C_Butcher_H_BombDock_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 696, 85, 85}},
	C_Butcher_H_BombDock_Breaking = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 609, 85, 85}},
	C_Butcher_H_BombDock_Done = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 261, 85, 85}},
	C_Butcher_H_BombDock_HighTimes = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 522, 85, 85}},
	C_Butcher_H_BombDock_IveGot = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 174, 85, 85}},
	C_Butcher_H_BombDock_Sneaking_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {522, 261, 85, 85}},
	C_Butcher_H_BombForest_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 348, 85, 85}},
	C_Butcher_H_BombForest_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 348, 85, 85}},
	C_Butcher_H_BombForest_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {87, 87, 85, 85}},
	C_Butcher_H_BombForest_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {435, 174, 85, 85}},
	C_Butcher_H_BombForest_Beaver = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {696, 870, 85, 85}},
	C_Butcher_H_BombForest_Oppressor = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 522, 85, 85}},
	C_Butcher_H_BombForest_PumpIt = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {435, 609, 85, 85}},
	C_Butcher_H_Scarface_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {261, 348, 85, 85}},
	C_Butcher_H_Scarface_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {696, 87, 85, 85}},
	C_Butcher_H_Scarface_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 609, 85, 85}},
	C_Butcher_H_Scarface_LookAtThese = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 348, 85, 85}},
	C_Butcher_H_Scarface_SayHello_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 348, 85, 85}},
	C_Butcher_H_Scarface_WhatYouWant_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 870, 85, 85}},
	C_Classics_H_Counterfeit_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {435, 87, 85, 85}},
	C_Classics_H_Counterfeit_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {870, 261, 85, 85}},
	C_Classics_H_Counterfeit_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {609, 609, 85, 85}},
	C_Classics_H_Counterfeit_Basement_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 522, 85, 85}},
	C_Classics_H_Counterfeit_Crowd = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {609, 609, 85, 85}},
	C_Classics_H_Counterfeit_CuttingTheRed_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 0, 85, 85}},
	C_Classics_H_Counterfeit_DrEvil = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 261, 85, 85}},
	C_Classics_H_FirstWorldBank_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {609, 0, 85, 85}},
	C_Classics_H_FirstWorldBank_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {174, 435, 85, 85}},
	C_Classics_H_FirstWorldBank_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {174, 87, 85, 85}},
	C_Classics_H_FirstWorldBank_Au = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 261, 85, 85}},
	C_Classics_H_FirstWorldBank_Cloaker_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 522, 85, 85}},
	C_Classics_H_FirstWorldBank_Hidden = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 0, 85, 85}},
	C_Classics_H_FirstWorldBank_LEET = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 783, 85, 85}},
	C_Classics_H_FirstWorldBank_Original_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {435, 261, 85, 85}},
	C_Classics_H_FirstWorldBank_Overdrill_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {87, 87, 85, 85}},
	C_Classics_H_GreenBridge_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {870, 783, 85, 85}},
	C_Classics_H_GreenBridge_AllDiffs_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {0, 783, 85, 85}},
	C_Classics_H_GreenBridge_AllDiffs_D2 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 0, 85, 85}},
	C_Classics_H_GreenBridge_AllDiffs_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {174, 348, 85, 85}},
	C_Classics_H_GreenBridge_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 435, 85, 85}},
	C_Classics_H_GreenBridge_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {0, 87, 85, 85}},
	C_Classics_H_GreenBridge_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {261, 87, 85, 85}},
	C_Classics_H_GreenBridge_BackToPrison = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 0, 85, 85}},
	C_Classics_H_GreenBridge_Caution = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {174, 696, 85, 85}},
	C_Classics_H_GreenBridge_FeltBad = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {0, 522, 85, 85}},
	C_Classics_H_HeatStreet_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 696, 85, 85}},
	C_Classics_H_HeatStreet_AllDiffs_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 0, 85, 85}},
	C_Classics_H_HeatStreet_AllDiffs_D2 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {783, 522, 85, 85}},
	C_Classics_H_HeatStreet_AllDiffs_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {0, 0, 85, 85}},
	C_Classics_H_HeatStreet_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 261, 85, 85}},
	C_Classics_H_HeatStreet_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {0, 87, 85, 85}},
	C_Classics_H_HeatStreet_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 522, 85, 85}},
	C_Classics_H_HeatStreet_ItsNice = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 87, 85, 85}},
	C_Classics_H_HeatStreet_Patience = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 609, 85, 85}},
	C_Classics_H_HeatStreet_Zookeeper = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {870, 870, 85, 85}},
	C_Classics_H_PanicRoom_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {609, 261, 85, 85}},
	C_Classics_H_PanicRoom_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 0, 85, 85}},
	C_Classics_H_PanicRoom_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 435, 85, 85}},
	C_Classics_H_PanicRoom_Cardio = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 783, 85, 85}},
	C_Classics_H_PanicRoom_DontYouDare = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 522, 85, 85}},
	C_Classics_H_PanicRoom_TheDentist = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {87, 696, 85, 85}},
	C_Classics_H_Slaughterhouse_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {174, 696, 85, 85}},
	C_Classics_H_Slaughterhouse_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 696, 85, 85}},
	C_Classics_H_Slaughterhouse_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {870, 609, 85, 85}},
	C_Classics_H_Slaughterhouse_ButHow = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {609, 696, 85, 85}},
	C_Classics_H_Slaughterhouse_Making_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 783, 85, 85}},
	C_Classics_H_Slaughterhouse_NotHard_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {870, 0, 85, 85}},
	C_Classics_H_Slaughterhouse_PorkRoyale_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {174, 783, 85, 85}},
	C_Classics_H_Slaughterhouse_Pyromaniacs = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {261, 261, 85, 85}},
	C_Classics_H_Undercover_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {435, 870, 85, 85}},
	C_Classics_H_Undercover_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {783, 609, 85, 85}},
	C_Classics_H_Undercover_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 870, 85, 85}},
	C_Classics_H_Undercover_BlowOut_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {87, 174, 85, 85}},
	C_Classics_H_Undercover_KeepClear = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 0, 85, 85}},
	C_Classics_H_Undercover_NotEven_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 609, 85, 85}},
	C_Classics_H_Undercover_TheSaviour = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {435, 522, 85, 85}},
	C_Continental_H_Brooklyn_ARendezvous_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 0, 85, 85}},
	C_Continental_H_Brooklyn_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {696, 522, 85, 85}},
	C_Continental_H_Brooklyn_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 348, 85, 85}},
	C_Continental_H_Brooklyn_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {609, 174, 85, 85}},
	C_Continental_H_Brooklyn_Apartment_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 783, 85, 85}},
	C_Continental_H_Brooklyn_PassTheAmmo_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 522, 85, 85}},
	C_Continental_H_YachtHeist_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 348, 85, 85}},
	C_Continental_H_YachtHeist_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {696, 174, 85, 85}},
	C_Continental_H_YachtHeist_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {174, 348, 85, 85}},
	C_Continental_H_YachtHeist_Blood = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {609, 870, 85, 85}},
	C_Continental_H_YachtHeist_Pacifish = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 87, 85, 85}},
	C_Continental_H_YachtHeist_Thalasso_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 174, 85, 85}},
	C_Dentist_H_BigBank_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 348, 85, 85}},
	C_Dentist_H_BigBank_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 435, 85, 85}},
	C_Dentist_H_BigBank_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 783, 85, 85}},
	C_Dentist_H_BigBank_Backing = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {0, 174, 85, 85}},
	C_Dentist_H_BigBank_DontBring = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 87, 85, 85}},
	C_Dentist_H_BigBank_Entrapment = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 435, 85, 85}},
	C_Dentist_H_BigBank_FundingFather = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {348, 696, 85, 85}},
	C_Dentist_H_BigBank_ItTakesAPig = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 609, 85, 85}},
	C_Dentist_H_BigBank_ItTakesTwo = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 609, 85, 85}},
	C_Dentist_H_BigBank_SweetSixteen = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 0, 85, 85}},
	C_Dentist_H_BigBank_TwelveAngry_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {522, 696, 85, 85}},
	C_Dentist_H_BigBank_YouOweMeOne = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {87, 783, 85, 85}},
	C_Dentist_H_Diamond_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 174, 85, 85}},
	C_Dentist_H_Diamond_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 783, 85, 85}},
	C_Dentist_H_Diamond_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {870, 348, 85, 85}},
	C_Dentist_H_Diamond_CatBurglar = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 348, 85, 85}},
	C_Dentist_H_Diamond_Culture = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {87, 783, 85, 85}},
	C_Dentist_H_Diamond_Diamonds_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 435, 85, 85}},
	C_Dentist_H_Diamond_Honor_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 87, 85, 85}},
	C_Dentist_H_Diamond_Smoke = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 783, 85, 85}},
	C_Dentist_H_GoldenGrinCasino_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {870, 870, 85, 85}},
	C_Dentist_H_GoldenGrinCasino_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 696, 85, 85}},
	C_Dentist_H_GoldenGrinCasino_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 870, 85, 85}},
	C_Dentist_H_GoldenGrinCasino_BlindEye = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 609, 85, 85}},
	C_Dentist_H_GoldenGrinCasino_CityofSin = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 0, 85, 85}},
	C_Dentist_H_GoldenGrinCasino_HailtotheKing = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 696, 85, 85}},
	C_Dentist_H_GoldenGrinCasino_HighRoller = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 0, 85, 85}},
	C_Dentist_H_HotlineMiami_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {174, 0, 85, 85}},
	C_Dentist_H_HotlineMiami_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 783, 85, 85}},
	C_Dentist_H_HotlineMiami_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 435, 85, 85}},
	C_Dentist_H_HotlineMiami_DoYouLike = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 435, 85, 85}},
	C_Dentist_H_HotlineMiami_Overdose = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 87, 85, 85}},
	C_Dentist_H_HotlineMiami_Phew = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 522, 85, 85}},
	C_Dentist_H_HotlineMiami_SoundsofAnimals_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 261, 85, 85}},
	C_Dentist_H_HoxtonBreakout_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {348, 261, 85, 85}},
	C_Dentist_H_HoxtonBreakout_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 0, 85, 85}},
	C_Dentist_H_HoxtonBreakout_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 522, 85, 85}},
	C_Dentist_H_HoxtonBreakout_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {696, 0, 85, 85}},
	C_Dentist_H_HoxtonBreakout_SituationNormal_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 870, 85, 85}},
	C_Dentist_H_HoxtonBreakout_TabulaRasa_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {870, 174, 85, 85}},
	C_Dentist_H_HoxtonBreakout_WalkFaster_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 522, 85, 85}},
	C_Dentist_H_HoxtonBreakout_Wind_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {609, 696, 85, 85}},
	C_Dentist_H_HoxtonRevenge_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 696, 85, 85}},
	C_Dentist_H_HoxtonRevenge_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {435, 174, 85, 85}},
	C_Dentist_H_HoxtonRevenge_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {87, 435, 85, 85}},
	C_Dentist_H_HoxtonRevenge_Silent = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 261, 85, 85}},
	C_Elephant_H_All_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 870, 85, 85}},
	C_Elephant_H_All_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {348, 435, 85, 85}},
	C_Elephant_H_All_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 87, 85, 85}},
	C_Elephant_H_BigOil_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 696, 85, 85}},
	C_Elephant_H_BigOil_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 0, 85, 85}},
	C_Elephant_H_BigOil_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {609, 870, 85, 85}},
	C_Elephant_H_BigOil_BostonSaints_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 87, 85, 85}},
	C_Elephant_H_BigOil_DoctorFantastic = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 696, 85, 85}},
	C_Elephant_H_BigOil_DoctorMiserable_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {0, 609, 85, 85}},
	C_Elephant_H_BigOil_HouseKeeping_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 174, 85, 85}},
	C_Elephant_H_BigOil_IKnewWhatIDid = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {435, 696, 85, 85}},
	C_Elephant_H_Biker_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {522, 783, 85, 85}},
	C_Elephant_H_Biker_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 174, 85, 85}},
	C_Elephant_H_Biker_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 696, 85, 85}},
	C_Elephant_H_Biker_EyeforanEye = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {435, 696, 85, 85}},
	C_Elephant_H_Biker_FullThrottle_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 870, 85, 85}},
	C_Elephant_H_Biker_LetTheMan_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {0, 174, 85, 85}},
	C_Elephant_H_Biker_Scavenger = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {0, 0, 85, 85}},
	C_Elephant_H_ElectionDay_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {783, 870, 85, 85}},
	C_Elephant_H_ElectionDay_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 870, 85, 85}},
	C_Elephant_H_ElectionDay_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {435, 87, 85, 85}},
	C_Elephant_H_ElectionDay_DeathWishSwinger_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 609, 85, 85}},
	C_Elephant_H_ElectionDay_HotLava = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {696, 522, 85, 85}},
	C_Elephant_H_ElectionDay_ImASwinger = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 348, 85, 85}},
	C_Elephant_H_ElectionDay_MasterDetective = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {870, 261, 85, 85}},
	C_Elephant_H_ElectionDay_Murphy = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 174, 85, 85}},
	C_Elephant_H_ElectionDay_Reputation_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 87, 85, 85}},
	C_Elephant_H_ElectionDay_Speedlock = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 696, 85, 85}},
	C_Elephant_H_ElectionDay_StorageHunter = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 348, 85, 85}},
	C_Elephant_H_FramingFrame_Afraid = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {174, 696, 85, 85}},
	C_Elephant_H_FramingFrame_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {435, 522, 85, 85}},
	C_Elephant_H_FramingFrame_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {87, 870, 85, 85}},
	C_Elephant_H_FramingFrame_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 87, 85, 85}},
	C_Elephant_H_FramingFrame_BigDeal = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 261, 85, 85}},
	C_Elephant_H_FramingFrame_IWasnt = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 261, 85, 85}},
	C_Elephant_H_FramingFrame_PaintingYourself = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 783, 85, 85}},
	C_Elephant_H_FramingFrame_WeDoIt_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 609, 85, 85}},
	C_Escape_H_Cafe_Cappuccino = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {261, 174, 85, 85}},
	C_Escape_H_Garage_TheySeeMe = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {261, 435, 85, 85}},
	C_Escape_H_Overpass_YouShallNot = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 435, 85, 85}},
	C_Escape_H_Park_King = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 696, 85, 85}},
	C_Escape_H_Street_Bullet = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 609, 85, 85}},
	C_Event_H_LabRats_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 348, 85, 85}},
	C_Event_H_LabRats_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {435, 870, 85, 85}},
	C_Event_H_LabRats_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 522, 85, 85}},
	C_Event_H_LabRats_Skill = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {174, 174, 85, 85}},
	C_Event_H_LabRats_TrickorTreat_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {0, 783, 85, 85}},
	C_Event_H_PrisonNightmare_ALongNight_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {609, 87, 85, 85}},
	C_Event_H_PrisonNightmare_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 696, 85, 85}},
	C_Event_H_PrisonNightmare_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 0, 85, 85}},
	C_Event_H_PrisonNightmare_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 0, 85, 85}},
	C_Event_H_PrisonNightmare_HesGotExperience_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {870, 261, 85, 85}},
	C_Event_H_PrisonNightmare_SalemAsylum_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {0, 348, 85, 85}},
	C_Event_H_SafeHouseNightmare_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 609, 85, 85}},
	C_Event_H_SafeHouseNightmare_AllDiffs_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {435, 174, 85, 85}},
	C_Event_H_SafeHouseNightmare_AllDiffs_D2 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 783, 85, 85}},
	C_Event_H_SafeHouseNightmare_AllDiffs_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {696, 174, 85, 85}},
	C_Event_H_SafeHouseNightmare_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {87, 522, 85, 85}},
	C_Event_H_SafeHouseNightmare_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 870, 85, 85}},
	C_Event_H_SafeHouseNightmare_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {87, 87, 85, 85}},
	C_Hector_H_All_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 870, 85, 85}},
	C_Hector_H_All_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {174, 870, 85, 85}},
	C_Hector_H_All_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 174, 85, 85}},
	C_Hector_H_Firestarter_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 435, 85, 85}},
	C_Hector_H_Firestarter_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 174, 85, 85}},
	C_Hector_H_Firestarter_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 609, 85, 85}},
	C_Hector_H_Firestarter_ForDaisy_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {696, 0, 85, 85}},
	C_Hector_H_Firestarter_Guessing = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 609, 85, 85}},
	C_Hector_H_Firestarter_HereComesThePain_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 174, 85, 85}},
	C_Hector_H_Firestarter_ItsGettingHot_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 174, 85, 85}},
	C_Hector_H_Firestarter_Lord = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 348, 85, 85}},
	C_Hector_H_Firestarter_TheFirst = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {87, 174, 85, 85}},
	C_Hector_H_Firestarter_Wasteful_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 87, 85, 85}},
	C_Hector_H_Firestarter_YouCanRun_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {870, 87, 85, 85}},
	C_Hector_H_Rats_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 609, 85, 85}},
	C_Hector_H_Rats_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 174, 85, 85}},
	C_Hector_H_Rats_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {696, 696, 85, 85}},
	C_Hector_H_Rats_Caribbean = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 0, 85, 85}},
	C_Hector_H_Rats_Cooking_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 696, 85, 85}},
	C_Hector_H_Rats_FinChem = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {609, 174, 85, 85}},
	C_Hector_H_Rats_FourMonkeys_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 261, 85, 85}},
	C_Hector_H_Rats_FullMeasure_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 870, 85, 85}},
	C_Hector_H_Rats_IAmTheOne = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {435, 0, 85, 85}},
	C_Hector_H_Rats_Short = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {783, 174, 85, 85}},
	C_Hector_H_Watchdogs_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 0, 85, 85}},
	C_Hector_H_Watchdogs_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {435, 609, 85, 85}},
	C_Hector_H_Watchdogs_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 435, 85, 85}},
	C_Hector_H_Watchdogs_Coming = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {174, 435, 85, 85}},
	C_Hector_H_Watchdogs_Fish = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 783, 85, 85}},
	C_Hector_H_Watchdogs_Unusual_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 348, 85, 85}},
	C_Hector_H_Watchdogs_WeAreRockstars_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {261, 609, 85, 85}},
	C_Hoxton_H_SafeHouse_Tip = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 261, 85, 85}},
	C_Jimmy_H_Boiling_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {0, 609, 85, 85}},
	C_Jimmy_H_Boiling_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {348, 261, 85, 85}},
	C_Jimmy_H_Boiling_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 522, 85, 85}},
	C_Jimmy_H_Boiling_CrazyIvan_D2 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 522, 85, 85}},
	C_Jimmy_H_Boiling_TheGround_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 870, 85, 85}},
	C_Jimmy_H_Boiling_UMPForMe_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 696, 85, 85}},
	C_Jimmy_H_Boiling_WhenInRussia_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 696, 85, 85}},
	C_Jimmy_H_MurkyStation_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {609, 435, 85, 85}},
	C_Jimmy_H_MurkyStation_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 696, 85, 85}},
	C_Jimmy_H_MurkyStation_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {348, 696, 85, 85}},
	C_Jimmy_H_MurkyStation_CrouchedandHidden = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {0, 522, 85, 85}},
	C_Jimmy_H_MurkyStation_GhostRun = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {0, 435, 85, 85}},
	C_Jimmy_H_MurkyStation_Janitor = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 522, 85, 85}},
	C_Jimmy_H_MurkyStation_Lootinh_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {696, 435, 85, 85}},
	C_Jimmy_H_MurkyStation_NoWitnesses_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {0, 696, 85, 85}},
	C_Jimmy_H_MurkyStation_ThePacifist = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 348, 85, 85}},
	C_Locke_H_Beneath_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 522, 85, 85}},
	C_Locke_H_Beneath_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {870, 783, 85, 85}},
	C_Locke_H_Beneath_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {87, 522, 85, 85}},
	C_Locke_H_Beneath_Clean = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {609, 609, 85, 85}},
	C_Locke_H_Beneath_Commando_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 522, 85, 85}},
	C_Locke_H_Beneath_Juggernauts_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {783, 435, 85, 85}},
	C_Locke_H_BirthOfSky_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {261, 522, 85, 85}},
	C_Locke_H_BirthOfSky_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {348, 609, 85, 85}},
	C_Locke_H_BirthOfSky_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {87, 783, 85, 85}},
	C_Locke_H_BirthOfSky_BlackTie_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {435, 0, 85, 85}},
	C_Locke_H_BirthOfSky_Mellon = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 87, 85, 85}},
	C_Locke_H_BirthOfSky_NoBlood_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 609, 85, 85}},
	C_Locke_H_BirthOfSky_OneTwoThree_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 0, 85, 85}},
	C_Locke_H_BirthOfSky_Pinpoint = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {783, 522, 85, 85}},
	C_Vlad_H_Aftershock_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {435, 783, 85, 85}},
	C_Vlad_H_Aftershock_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 87, 85, 85}},
	C_Vlad_H_Aftershock_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {261, 174, 85, 85}},
	C_Vlad_H_Aftershock_FourHundredBucks = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 261, 85, 85}},
	C_Vlad_H_All_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 609, 85, 85}},
	C_Vlad_H_All_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 609, 85, 85}},
	C_Vlad_H_All_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {0, 783, 85, 85}},
	C_Vlad_H_FourStores_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 783, 85, 85}},
	C_Vlad_H_FourStores_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {87, 696, 85, 85}},
	C_Vlad_H_FourStores_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {435, 348, 85, 85}},
	C_Vlad_H_FourStores_YeahHe = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 261, 85, 85}},
	C_Vlad_H_GoatSim_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 261, 85, 85}},
	C_Vlad_H_GoatSim_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {522, 435, 85, 85}},
	C_Vlad_H_GoatSim_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {609, 261, 85, 85}},
	C_Vlad_H_GoatSim_Baaaa = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 609, 85, 85}},
	C_Vlad_H_GoatSim_FarmerMiserable_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 87, 85, 85}},
	C_Vlad_H_GoatSim_GoatIn = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 261, 85, 85}},
	C_Vlad_H_GoatSim_Hazzard = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 174, 85, 85}},
	C_Vlad_H_Mallcrasher_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 174, 85, 85}},
	C_Vlad_H_Mallcrasher_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 696, 85, 85}},
	C_Vlad_H_Mallcrasher_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {783, 174, 85, 85}},
	C_Vlad_H_Mallcrasher_OnePointEight_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {87, 348, 85, 85}},
	C_Vlad_H_Mallcrasher_Shoot = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 783, 85, 85}},
	C_Vlad_H_Meltdown_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {522, 261, 85, 85}},
	C_Vlad_H_Meltdown_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 870, 85, 85}},
	C_Vlad_H_Meltdown_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {435, 348, 85, 85}},
	C_Vlad_H_Meltdown_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {87, 522, 85, 85}},
	C_Vlad_H_Meltdown_ThereWas = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 87, 85, 85}},
	C_Vlad_H_Meltdown_TheyDontPay = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 522, 85, 85}},
	C_Vlad_H_Nightclub_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 696, 85, 85}},
	C_Vlad_H_Nightclub_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {870, 174, 85, 85}},
	C_Vlad_H_Nightclub_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 87, 85, 85}},
	C_Vlad_H_Nightclub_Everyday = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {348, 783, 85, 85}},
	C_Vlad_H_Nightclub_HeyMr = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {87, 174, 85, 85}},
	C_Vlad_H_Nightclub_ImGoing = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 435, 85, 85}},
	C_Vlad_H_Nightclub_KeeptheParty = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {348, 870, 85, 85}},
	C_Vlad_H_Nightclub_OVESAW = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 870, 85, 85}},
	C_Vlad_H_Nightclub_TheEighth = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 174, 85, 85}},
	C_Vlad_H_Santa_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 0, 85, 85}},
	C_Vlad_H_Santa_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {348, 348, 85, 85}},
	C_Vlad_H_Santa_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 870, 85, 85}},
	C_Vlad_H_Santa_EuroBag_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 609, 85, 85}},
	C_Vlad_H_Santa_OnlySanta = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 174, 85, 85}},
	C_Vlad_H_Santa_PumpedUp = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 783, 85, 85}},
	C_Vlad_H_Santa_SantaSlays_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {261, 522, 85, 85}},
	C_Vlad_H_StealingXmas_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {261, 609, 85, 85}},
	C_Vlad_H_StealingXmas_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 696, 85, 85}},
	C_Vlad_H_StealingXmas_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {435, 870, 85, 85}},
	C_Vlad_H_StealingXmas_Christmas = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 87, 85, 85}},
	C_Vlad_H_StealingXmas_Grinch_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {261, 435, 85, 85}},
	C_Vlad_H_StealingXmas_Imitations = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {348, 87, 85, 85}},
	C_Vlad_H_Ukrainian_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {870, 783, 85, 85}},
	C_Vlad_H_Ukrainian_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {696, 435, 85, 85}},
	C_Vlad_H_Ukrainian_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {0, 174, 85, 85}},
	C_Vlad_H_Ukrainian_LetsDoTh = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {609, 870, 85, 85}},
	C_Vlad_H_XMas_AllDiffs_D0 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 870, 85, 85}},
	C_Vlad_H_XMas_AllDiffs_D1 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {261, 0, 85, 85}},
	C_Vlad_H_XMas_AllDiffs_D2 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 435, 85, 85}},
	C_Vlad_H_XMas_AllDiffs_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {0, 435, 85, 85}},
	C_Vlad_H_XMas_AllDiffs_D4 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {783, 696, 85, 85}},
	C_Vlad_H_XMas_AllDiffs_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {261, 783, 85, 85}},
	C_Vlad_H_XMas_AllDiffs_D6 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 174, 85, 85}},
	C_Vlad_H_XMas_Impossible = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {609, 522, 85, 85}},
	C_Vlad_H_XMas_Riders_D5 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 435, 85, 85}},
	Other_H_Any_ATaste = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 348, 85, 85}},
	Other_H_Any_AboveTheLaw = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 348, 85, 85}},
	Other_H_Any_Affordable = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {696, 870, 85, 85}},
	Other_H_Any_AreYouKidding = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {348, 174, 85, 85}},
	Other_H_Any_Artillery = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {435, 261, 85, 85}},
	Other_H_Any_Bang = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {87, 174, 85, 85}},
	Other_H_Any_BigBadaBoom = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {0, 261, 85, 85}},
	Other_H_Any_BlackKnight = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 783, 85, 85}},
	Other_H_Any_BringYourCop_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {609, 609, 85, 85}},
	Other_H_Any_Bullet = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 0, 85, 85}},
	Other_H_Any_BullsEye = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {87, 783, 85, 85}},
	Other_H_Any_Bunnyhopping = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {609, 348, 85, 85}},
	Other_H_Any_Cavity = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {261, 522, 85, 85}},
	Other_H_Any_CelsiusOr_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 522, 85, 85}},
	Other_H_Any_ClayPigeon = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 0, 85, 85}},
	Other_H_Any_Cloak = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 783, 85, 85}},
	Other_H_Any_Commando = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {870, 696, 85, 85}},
	Other_H_Any_CrimeSpree050 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {870, 696, 85, 85}},
	Other_H_Any_CrimeSpree100 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 783, 85, 85}},
	Other_H_Any_CrimeSpree250 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {609, 174, 85, 85}},
	Other_H_Any_DeathFrom = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 522, 85, 85}},
	Other_H_Any_DidntSee = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 348, 85, 85}},
	Other_H_Any_DiscoInferno = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {870, 435, 85, 85}},
	Other_H_Any_Dodge = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {870, 0, 85, 85}},
	Other_H_Any_Dont = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {87, 261, 85, 85}},
	Other_H_Any_DoubleKill = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 261, 85, 85}},
	Other_H_Any_Ducking = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 609, 85, 85}},
	Other_H_Any_EagleEyes = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 783, 85, 85}},
	Other_H_Any_FarFar = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {696, 609, 85, 85}},
	Other_H_Any_FastestGun = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 348, 85, 85}},
	Other_H_Any_FireInTheHole = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {870, 87, 85, 85}},
	Other_H_Any_FoolMe = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {261, 870, 85, 85}},
	Other_H_Any_FromRussia_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {174, 0, 85, 85}},
	Other_H_Any_Fugu = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {87, 870, 85, 85}},
	Other_H_Any_GhostRiders = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {174, 609, 85, 85}},
	Other_H_Any_Hammertime = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {87, 87, 85, 85}},
	Other_H_Any_HardCorps = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 261, 85, 85}},
	Other_H_Any_Hedgehog = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 609, 85, 85}},
	Other_H_Any_Heisters_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 0, 85, 85}},
	Other_H_Any_Holy = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 174, 85, 85}},
	Other_H_Any_IAintGotTime_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {87, 435, 85, 85}},
	Other_H_Any_IAmAn = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 435, 85, 85}},
	Other_H_Any_IDidNot = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {696, 783, 85, 85}},
	Other_H_Any_IGotIt = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {870, 261, 85, 85}},
	Other_H_Any_INeverAsked = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 696, 85, 85}},
	Other_H_Any_IWant = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {174, 435, 85, 85}},
	Other_H_Any_ImNot = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 435, 85, 85}},
	Other_H_Any_InTown = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {174, 261, 85, 85}},
	Other_H_Any_Inception = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {696, 696, 85, 85}},
	Other_H_Any_ItsAlive = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 870, 85, 85}},
	Other_H_Any_JumpJump = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {174, 522, 85, 85}},
	Other_H_Any_KillinsAsEasy = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 783, 85, 85}},
	Other_H_Any_KnockKnock = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 261, 85, 85}},
	Other_H_Any_Knockout = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 609, 85, 85}},
	Other_H_Any_LastAction = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 870, 85, 85}},
	Other_H_Any_LetThem = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {87, 348, 85, 85}},
	Other_H_Any_License = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {261, 696, 85, 85}},
	Other_H_Any_LikeABoy = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {609, 87, 85, 85}},
	Other_H_Any_LockStock = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 348, 85, 85}},
	Other_H_Any_Maximum = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {522, 609, 85, 85}},
	Other_H_Any_Megalo = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 87, 85, 85}},
	Other_H_Any_MySpiderSense = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 87, 85, 85}},
	Other_H_Any_NamesAreFor = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {870, 435, 85, 85}},
	Other_H_Any_NoHeist = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {609, 609, 85, 85}},
	Other_H_Any_NoOneCan = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 174, 85, 85}},
	Other_H_Any_NoOneCared = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {435, 435, 85, 85}},
	Other_H_Any_NoScope = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {174, 174, 85, 85}},
	Other_H_Any_NotInvited = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {522, 348, 85, 85}},
	Other_H_Any_NotToday = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 783, 85, 85}},
	Other_H_Any_Nothing = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {87, 261, 85, 85}},
	Other_H_Any_NothingPersonal_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 783, 85, 85}},
	Other_H_Any_OVERGRILL = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {87, 435, 85, 85}},
	Other_H_Any_OhThatsHow = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {174, 870, 85, 85}},
	Other_H_Any_OneHoundredTwenty = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 174, 85, 85}},
	Other_H_Any_Pink = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 783, 85, 85}},
	Other_H_Any_PoliceBrutality = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {261, 174, 85, 85}},
	Other_H_Any_PrayingMantis = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {609, 87, 85, 85}},
	Other_H_Any_Precision = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {696, 261, 85, 85}},
	Other_H_Any_PublicEnemies = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {348, 870, 85, 85}},
	Other_H_Any_PublicEnemy = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 348, 85, 85}},
	Other_H_Any_PumpAction = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 609, 85, 85}},
	Other_H_Any_Rabbit = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {435, 870, 85, 85}},
	Other_H_Any_Recycling = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {870, 522, 85, 85}},
	Other_H_Any_Reindeer = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {261, 0, 85, 85}},
	Other_H_Any_SevenEleven = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {261, 261, 85, 85}},
	Other_H_Any_ShareTheLove = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {0, 348, 85, 85}},
	Other_H_Any_ShockAndAwe = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {87, 348, 85, 85}},
	Other_H_Any_Shotgun = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {0, 870, 85, 85}},
	Other_H_Any_Shuriken = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {348, 609, 85, 85}},
	Other_H_Any_Sinper_Kills_050 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {435, 522, 85, 85}},
	Other_H_Any_Sinper_Kills_100 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {522, 435, 85, 85}},
	Other_H_Any_Sinper_Kills_250 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 783, 85, 85}},
	Other_H_Any_Sinper_Kills_500 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {261, 696, 85, 85}},
	Other_H_Any_Skewer = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {783, 522, 85, 85}},
	Other_H_Any_SoMany = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {348, 870, 85, 85}},
	Other_H_Any_SpecialOp = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {0, 522, 85, 85}},
	Other_H_Any_StickAFork = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {0, 696, 85, 85}},
	Other_H_Any_Surprise = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {174, 87, 85, 85}},
	Other_H_Any_Swing = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {174, 696, 85, 85}},
	Other_H_Any_Swiss = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {783, 609, 85, 85}},
	Other_H_Any_TheCollector = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {522, 174, 85, 85}},
	Other_H_Any_TheManWith = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 87, 85, 85}},
	Other_H_Any_TheNobel = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {522, 522, 85, 85}},
	Other_H_Any_TheOneThatHad = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {870, 609, 85, 85}},
	Other_H_Any_TheOneThatSurvived = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 348, 85, 85}},
	Other_H_Any_TheOneWhoDeclared = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {696, 435, 85, 85}},
	Other_H_Any_TheOnlyOne = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {522, 696, 85, 85}},
	Other_H_Any_ThePumpkinKing = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {0, 522, 85, 85}},
	Other_H_Any_TheReconing_D2 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {609, 174, 85, 85}},
	Other_H_Any_TheirArmor = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {870, 435, 85, 85}},
	Other_H_Any_ThereAndBack = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 435, 85, 85}},
	Other_H_Any_TheyDrewFirst = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {783, 696, 85, 85}},
	Other_H_Any_ThreeThousandMiles = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {522, 696, 85, 85}},
	Other_H_Any_TourDeClarion = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {435, 0, 85, 85}},
	Other_H_Any_TripleKill = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {609, 696, 85, 85}},
	Other_H_Any_Wanted = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 609, 85, 85}},
	Other_H_Any_WitchDoctor = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {348, 174, 85, 85}},
	Other_H_Any_YouCant = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {870, 522, 85, 85}},
	Other_H_None_AVote = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {174, 870, 85, 85}},
	Other_H_None_Armed = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {696, 0, 85, 85}},
	Other_H_None_ArmyofOne = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 696, 85, 85}},
	Other_H_None_BuildMe = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {87, 609, 85, 85}},
	Other_H_None_ChristmasCame = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {87, 435, 85, 85}},
	Other_H_None_FullyLoaded = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {609, 435, 85, 85}},
	Other_H_None_GoingPlaces = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {348, 870, 85, 85}},
	Other_H_None_GunsAreLike = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas8", texture_rect = {0, 87, 85, 85}},
	Other_H_None_HaveNiceDay = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 174, 85, 85}},
	Other_H_None_Heat = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {0, 609, 85, 85}},
	Other_H_None_HighSpeed = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {696, 174, 85, 85}},
	Other_H_None_HowDoYou = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {174, 261, 85, 85}},
	Other_H_None_ImAHealerTank = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {348, 348, 85, 85}},
	Other_H_None_LikeAnAngry = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {783, 435, 85, 85}},
	Other_H_None_MallNinja = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {435, 87, 85, 85}},
	Other_H_None_ManOfIron = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {174, 261, 85, 85}},
	Other_H_None_Masked = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {174, 348, 85, 85}},
	Other_H_None_Merry = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {435, 609, 85, 85}},
	Other_H_None_Point = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas2", texture_rect = {87, 522, 85, 85}},
	Other_H_None_Russian = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {783, 522, 85, 85}},
	Other_H_None_RussianArsenal_D3 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas3", texture_rect = {870, 348, 85, 85}},
	Other_H_None_SeakyBeaky = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas5", texture_rect = {783, 261, 85, 85}},
	Other_H_None_SoUncivilized = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas4", texture_rect = {261, 696, 85, 85}},
	Other_H_None_SpendMoney = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas6", texture_rect = {609, 0, 85, 85}},
	Other_H_None_SprayControl = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {870, 87, 85, 85}},
	Other_H_None_Weapon = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {609, 435, 85, 85}},
	Other_H_None_WithAnIron = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas", texture_rect = {174, 522, 85, 85}},
	Other_H_None_WouldYouLike = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas7", texture_rect = {348, 522, 85, 85}},
}

for k, v in pairs(icons) do
	tweak_data.hud_icons[k] = v
end

if tweak_data.infamy and #tweak_data.infamy.tree == 5 then
	tweak_data.hud_icons.C_All_H_All_Infamy_02 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas_infamy_1_0", texture_rect = {0, 0, 85, 85}}
	tweak_data.hud_icons.C_All_H_All_Infamy_03 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas_infamy_1_0", texture_rect = {87, 0, 85, 85}}
	tweak_data.hud_icons.C_All_H_All_Infamy_04 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas_infamy_1_0", texture_rect = {174, 0, 85, 85}}
	tweak_data.hud_icons.C_All_H_All_Infamy_05 = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas_infamy_1_0", texture_rect = {261, 0, 85, 85}}
end

if not tweak_data.group_ai.enemy_spawn_groups.tac_swat_rifle_flank then
	local old_diff_icons = {
		"C_Bain_H_All_AllDiffs_D5",
		"C_Bain_H_Arena_AllDiffs_D5",
		"C_Bain_H_ArtGallery_AllDiffs_D5",
		"C_Bain_H_BankC_AllDiffs_D5",
		"C_Bain_H_BankD_AllDiffs_D5",
		"C_Bain_H_BankG_AllDiffs_D5",
		"C_Bain_H_BankR_AllDiffs_D5",
		"C_Bain_H_Car_AllDiffs_D5",
		"C_Bain_H_CookOff_AllDiffs_D5",
		"C_Bain_H_DiamondStore_AllDiffs_D5",
		"C_Bain_H_GOBank_AllDiffs_D5",
		"C_Bain_H_JewelryStore_AllDiffs_D5",
		"C_Bain_H_ShadowRaid_AllDiffs_D5",
		"C_Bain_H_TransportCrossroads_AllDiffs_D5",
		"C_Bain_H_TransportDowntown_AllDiffs_D5",
		"C_Bain_H_TransportHarbor_AllDiffs_D5",
		"C_Bain_H_TransportPark_AllDiffs_D5",
		"C_Bain_H_TransportTrainHeist_AllDiffs_D5",
		"C_Bain_H_TransportUnderpass_AllDiffs_D5",
		"C_Butcher_H_BombDock_AllDiffs_D5",
		"C_Butcher_H_BombForest_AllDiffs_D5",
		"C_Butcher_H_Scarface_AllDiffs_D5",
		"C_Classics_H_Counterfeit_AllDiffs_D5",
		"C_Classics_H_FirstWorldBank_AllDiffs_D5",
		"C_Classics_H_GreenBridge_AllDiffs_D5",
		"C_Classics_H_HeatStreet_AllDiffs_D5",
		"C_Classics_H_PanicRoom_AllDiffs_D5",
		"C_Classics_H_Slaughterhouse_AllDiffs_D5",
		"C_Classics_H_Undercover_AllDiffs_D5",
		"C_Continental_H_Brooklyn_AllDiffs_D5",
		"C_Continental_H_YachtHeist_AllDiffs_D5",
		"C_Dentist_H_BigBank_AllDiffs_D5",
		"C_Dentist_H_Diamond_AllDiffs_D5",
		"C_Dentist_H_GoldenGrinCasino_AllDiffs_D5",
		"C_Dentist_H_HotlineMiami_AllDiffs_D5",
		"C_Dentist_H_HoxtonBreakout_AllDiffs_D5",
		"C_Dentist_H_HoxtonRevenge_AllDiffs_D5",
		"C_Elephant_H_All_AllDiffs_D5",
		"C_Elephant_H_BigOil_AllDiffs_D5",
		"C_Elephant_H_Biker_AllDiffs_D5",
		"C_Elephant_H_ElectionDay_AllDiffs_D5",
		"C_Elephant_H_FramingFrame_AllDiffs_D5",
		"C_Event_H_LabRats_AllDiffs_D5",
		"C_Event_H_PrisonNightmare_AllDiffs_D5",
		"C_Event_H_SafeHouseNightmare_AllDiffs_D5",
		"C_Hector_H_All_AllDiffs_D5",
		"C_Hector_H_Firestarter_AllDiffs_D5",
		"C_Hector_H_Rats_AllDiffs_D5",
		"C_Hector_H_Watchdogs_AllDiffs_D5",
		"C_Jimmy_H_Boiling_AllDiffs_D5",
		"C_Jimmy_H_MurkyStation_AllDiffs_D5",
		"C_Locke_H_Beneath_AllDiffs_D5",
		"C_Locke_H_BirthOfSky_AllDiffs_D5",
		"C_Vlad_H_Aftershock_AllDiffs_D5",
		"C_Vlad_H_All_AllDiffs_D5",
		"C_Vlad_H_FourStores_AllDiffs_D5",
		"C_Vlad_H_GoatSim_AllDiffs_D5",
		"C_Vlad_H_Mallcrasher_AllDiffs_D5",
		"C_Vlad_H_Meltdown_AllDiffs_D5",
		"C_Vlad_H_Nightclub_AllDiffs_D5",
		"C_Vlad_H_Santa_AllDiffs_D5",
		"C_Vlad_H_StealingXmas_AllDiffs_D5",
		"C_Vlad_H_Ukrainian_AllDiffs_D5",
		"C_Vlad_H_XMas_AllDiffs_D5",
		"C_Dentist_H_HotlineMiami_Pro_AllDiffs_D5",
		"C_Dentist_H_HoxtonBreakout_Pro_AllDiffs_D5",
		"C_Elephant_H_Biker_Pro_AllDiffs_D5",
		"C_Elephant_H_ElectionDay_Pro_AllDiffs_D5",
		"C_Elephant_H_FramingFrame_Pro_AllDiffs_D5",
		"C_Hector_H_Firestarter_Pro_AllDiffs_D5",
		"C_Hector_H_Rats_Pro_AllDiffs_D5",
		"C_Hector_H_Watchdogs_Pro_AllDiffs_D5",
		"C_Vlad_H_GoatSim_Pro_AllDiffs_D5",
		"C_Elephant_H_ElectionDay_DeathWishSwinger_D5",
		"C_Elephant_H_ElectionDay_Reputation_D5",
		"C_Hector_H_Firestarter_Wasteful_D5",
		"C_Bain_H_BankAny_SaintFrancis_D3",
		"C_Bain_H_CookOff_KissTheChef_D3",
		"C_Classics_H_Counterfeit_Basement_D3",
		"C_Classics_H_Undercover_BlowOut_D3",
		"C_Classics_H_Undercover_NotEven_D3",
		"C_Event_H_SafeHouseNightmare_AllDiffs_D3",
		"C_Hector_H_Firestarter_YouCanRun_D3",
		"C_Jimmy_H_Boiling_WhenInRussia_D3",
		"C_Jimmy_H_MurkyStation_Lootinh_D3",
		"C_Locke_H_Beneath_Commando_D3",
		"C_Locke_H_Beneath_Juggernauts_D3",
		"C_Locke_H_BirthOfSky_BlackTie_D3",
		"C_Vlad_H_Santa_SantaSlays_D3",
		"C_Vlad_H_XMas_AllDiffs_D3",
		"C_Event_H_SafeHouseNightmare_AllDiffs_D2",
		"C_Vlad_H_XMas_AllDiffs_D2",
		"C_Event_H_SafeHouseNightmare_AllDiffs_D1",
		"C_Vlad_H_XMas_AllDiffs_D1",
		"C_Event_H_SafeHouseNightmare_AllDiffs_D0",
		"C_Vlad_H_XMas_AllDiffs_D0",
		"C_Butcher_H_BombDock_AllDiffs_D0",
		"C_Butcher_H_BombForest_AllDiffs_D0",
		"C_Dentist_H_HoxtonBreakout_AllDiffs_D0",
		"C_Vlad_H_Meltdown_AllDiffs_D0",
		"C_Hector_H_Firestarter_ItsGettingHot_D5",
	}

	local x = 0
	local y = 0
	for _, id in pairs(old_diff_icons) do
		tweak_data.hud_icons[id] = {texture = "guis/dlcs/trk/textures/pd2/achievements_atlas_old_diffs", texture_rect = {x, y, 85, 85}}

		if x == 870 then
			y = y + 87
			x = 0
		else
			x = x + 87
		end
	end
end